### ISSUE TITLE
Failing tests in Juniper-mist-integration

### ISSUE THREAD

**Issue by darey-io** [ministryofjustice/nvvs-devops#612]
Running tests from the main branch of the Juniper Mist Integration code is failing

python3 -m unittest discover -s test
E.......Continuing with run
..Username provided: test@example.com
.Login successful
Calling the Mist Create Site API...
Created site TestSite (123)

Retrieving the JSON response object...
{
    "id": "123",
    "name": "TestSite"
}

Using id in the Mist Update Setting API request
Calling the Mist Update Setting API...
Updated site setting TestSite (123)

Retrieving the JSON response object...
{
    "status": "success"
}

==========

.....Username provided: test@example.com
Login successful
.Login successful
POST https://api.eu.mist.com/some_endpoint
.Login successful
PUT https://api.eu.mist.com/some_endpoint
.E<MagicMock name='open().__enter__().read()' id='4397605456'>
A file containing all the changes has been created: ../data_src/mist_plan_20240124_084417.json
.<MagicMock name='open().__enter__().read()' id='4398816080'>
A file containing all the changes has been created: ../data_src/mist_plan_20240124_084417.json
.E
======================================================================
ERROR: test_geocode (unittest.loader._FailedTest.test_geocode)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_geocode
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/Users/dare.olufunmilayo/Desktop/moj/gitrepos/moj/juniper-mist/juniper-mist-integration/test/test_geocode.py", line 3, in <module>
    from src.geocode import geocode, find_timezone, find_country_code
  File "/Users/dare.olufunmilayo/Desktop/moj/gitrepos/moj/juniper-mist/juniper-mist-integration/src/geocode.py", line 2, in <module>
    from timezonefinder import TimezoneFinder
ModuleNotFoundError: No module named 'timezonefinder'

======================================================================
ERROR: test_plan_of_action_creates_file (test_juniper.TestPlanOfActionFunction.test_plan_of_action_creates_file)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dare.olufunmilayo/Desktop/moj/gitrepos/moj/juniper-mist/juniper-mist-integration/test/test_juniper.py", line 286, in test_plan_of_action_creates_file
    plan_of_action(self.data, self.rf_template_id,
  File "/Users/dare.olufunmilayo/Desktop/moj/gitrepos/moj/juniper-mist/juniper-mist-integration/src/juniper.py", line 307, in plan_of_action
    with open(plan_file_name, "w") as plan_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../data_src/mist_plan_20240124_084417.json'

======================================================================
ERROR: test_main (unittest.loader._FailedTest.test_main)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_main
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/Users/dare.olufunmilayo/Desktop/moj/gitrepos/moj/juniper-mist/juniper-mist-integration/test/test_main.py", line 5, in <module>
    from src.main import convert_csv_to_json, add_geocoding_to_json
  File "/Users/dare.olufunmilayo/Desktop/moj/gitrepos/moj/juniper-mist/juniper-mist-integration/src/main.py", line 3, in <module>
    from juniper import juniper_script
ModuleNotFoundError: No module named 'juniper'

----------------------------------------------------------------------
Ran 23 tests in 0.014s

FAILED (errors=3)

**Comment by jamesgreen-moj** [comment]
Closing this issue as the tests are working in main.

Tests are failing because it is being ran not via the make file:
How its being ran: 'python3 -m unittest discover -s test'
How it should be ran: 'make tests'

<img width="1850" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelQwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a33368530f87ab4b48a0c5c5dc21073de9c10da/image.png" alt="image.png" />


<img width="1300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekwwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f498a0a5efdab067e1e0b0d22ae7fe1f7bbd243/Screenshot%202024-01-24%20at%2009.33.32.png" alt="Screenshot 2024-01-24 at 09.33.32.png" />
